Section "ServerLayout"
    Identifier  "ToyiumLayout"
    Screen 0    "ToyiumScreen"
    InputDevice "ToyiumKeyboard" "CoreKeyboard"
    InputDevice "ToyiumMouse" "CorePointer"
    Option "AutoAddDevices" "off"
    Option "AllowMouseOpenFail" "on"
EndSection

Section "Module"
    Load "fbdevhw"
    Load "shadow"
    Load "shadowfb"
EndSection

Section "Monitor"
    Identifier  "ToyiumMonitor"
    HorizSync   1.0 - 1000.0
    VertRefresh 1.0 - 1000.0
    Option      "DPMS" "false"
EndSection

Section "Device"
    Identifier  "ToyiumCard"
    Driver      "fbdev"
    Option      "fbdev" "/dev/fb0"
    Option      "ShadowFB" "false"
EndSection

Section "Screen"
    Identifier  "ToyiumScreen"
    Device      "ToyiumCard"
    Monitor     "ToyiumMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth   24
        Modes   "1024x768"
    EndSubSection
EndSection

Section "InputDevice"
    Identifier  "ToyiumKeyboard"
    Driver      "evdev"
    Option      "Device" "/dev/input/event1"
    Option      "XkbLayout" "us"
EndSection

Section "InputDevice"
    Identifier  "ToyiumMouse"
    Driver      "evdev"
    Option      "Device" "/dev/input/event2"
EndSection
